flowchart LR

Bronhouder["Overheidsbron"]
DvTP["GBO<br />(afspraken, standaarden, voorzieningen)"]
Wallet["EDI-Wallet<br/>(EUDI)"]
SDG["OOTS<br/>(SDG)"]
Privaat["Private dienstverlener<br/>(DvTP)"]

Bronhouder --> DvTP
DvTP --> Wallet
DvTP --> SDG
DvTP --> Privaat
